version: '3.2'

services:
  api:
    container_name: auth-api-dev
    build:
      context: ./api/
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - $AUTH_PORT:$AUTH_PORT
    environment:
      MONGODB_URL: $MONGODB_URL
      JWT_KEY: $JWT_KEY
      AUTH_PORT: $AUTH_PORT
